version: "3.3"
volumes:
  data:
services:
  db:
    image: mysql:5.7
    ports:
      - "3000:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      # - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE:${MYSQL_DATABASE} 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_dev   
    networks:
      - admin-network   
      - php-network  
  admin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - admin-network
  app:
    build: ./
    ports:
      - 8080:80
    volumes:
      - /home/nate/docker:/var/www/html/
    networks:
      - php-network
networks:
    admin-network:
        driver: bridge
    php-network:
        driver: bridge